server:
  port: 8765

spring:
  application:
    name: api-gateway
  security:
    name : ahmed
    password : ahmed@777
#  cloud:
#    gateway:
#      routes:
#        - id: Microservice1
#          uri: http://localhost:8081/
#          Predicates:
#            - Path=/serviceA/**
#        - id: Microservice2
#          uri: http://localhost:8082/
#          Predicates:
#            - Path=/serviceB/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true